#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build & Publish `next` for arm

on:
  push:
    branches:
      - arm

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME:  ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD:  ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm64                 
    steps:
      - name: Checkout the code       
        uses: actions/checkout@v1          
      - name: Set up Docker Buildx      
        uses: crazy-max/ghaction-docker-buildx@v1      
        with:        
          version: latest    
      - name: Prepare      
        if: success()      
        id: prepare      
        run: |        
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
          echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
          echo ::set-output name=version::${GITHUB_RUN_NUMBER}    
      - uses: actions/setup-node@v1
        name: Configuring nodejs 12.x version
        with:
          node-version: '12.x'
      - name: Docker Login      
        if: success()      
        run: |        
         docker login --username "odidev" --password "nibble@123"
      - name: Run Buildx (push image)      
        if: success()      
        run: |        
          docker image prune -a -f
          ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine --push
        env:
          CDN_PREFIX: https://static.developers.redhat.com/che/theia_artifacts/
          MONACO_CDN_PREFIX: https://cdn.jsdelivr.net/npm/
      - name: Set-up npmjs auth token
        run: printf "//registry.npmjs.org/:_authToken=${{ secrets.CHE_NPM_AUTH_TOKEN }}\n" >> ~/.npmrc
      - name: Publish packages to npmjs
        run: yarn publish:next
